# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.cache/wt [current_project]
set_property parent.project_path C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.srcs/sources_1/new/Multiplier_5bit_FSM.vhd
  C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.srcs/sources_1/new/RCA_10bit.vhd
  C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.srcs/sources_1/new/sseg_dec_uni.vhd
  C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.srcs/sources_1/new/univ_sr_10bit.vhd
  C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.srcs/sources_1/new/univ_sr_5bit.vhd
  C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.srcs/sources_1/new/Multiplier_5bit.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.srcs/constrs_1/new/Multiplier_5bit_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Cole/Desktop/Multiplier_5bit/Multiplier_5bit.srcs/constrs_1/new/Multiplier_5bit_constraints.xdc]


synth_design -top Multiplier_5bit -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Multiplier_5bit.dcp

catch { report_utilization -file Multiplier_5bit_utilization_synth.rpt -pb Multiplier_5bit_utilization_synth.pb }
