# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ccummi08/COMP_8/COMP_8.cache/wt [current_project]
set_property parent.project_path C:/Users/ccummi08/COMP_8/COMP_8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/ccummi08/COMP_8/COMP_8.srcs/sources_1/new/COMP_4.vhd
  C:/Users/ccummi08/COMP_8/COMP_8.srcs/sources_1/new/COMP_8.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ccummi08/COMP_8/COMP_8.srcs/constrs_1/new/COMP_8_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/ccummi08/COMP_8/COMP_8.srcs/constrs_1/new/COMP_8_constraints.xdc]


synth_design -top COMP_8 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef COMP_8.dcp

catch { report_utilization -file COMP_8_utilization_synth.rpt -pb COMP_8_utilization_synth.pb }
